Install primary GLMM-fitting packages (and a variety of extras):

```{r pkg1,eval=FALSE}
pkgs1 <- c("afex", "agridat", "AICcmodavg", "aods3",
           "arm", "bbmle", "benchmark", 
           "blme", "cAIC4", "car",
           "coda", "dplyr", "effects", "emdbook", "gamm4", 
           "ggplot2", "glmmLasso", "glmmML", "gridExtra", "HLMdiag", "Hmisc",
           "influence.ME", "knitr", "lme4", "lmerTest", "lsmeans",
           "lqmm",
           "MCMCglmm", "MEMSS", "metafor", "mlmRev", "multcomp",
           "MuMIn", "numDeriv", "ordinal", "pbkrtest", "pedigreemm",
           "plotMCMC", "plotrix", "plyr", "R2admb", "R2jags",
           "reshape2", "RLRsim", "rmarkdown", "robustlmm", "rockchalk", 
           "SASmixed", "spGLMM", "stargazer", "texreg")
install.packages(pkgs1,dependencies=TRUE)
## get INLA:
source("http://www.math.ntnu.no/inla/givemeINLA.R")
```

`grid`, `nlme`, `MASS` should not need to be (re)installed, as they come with a standard R installation.  `scapeMCMC` (recommended in a previous version) is obsolete.

`coefplot2` and `glmmADMB` need to be gotten from off-CRAN repos:

```{r offCRAN,eval=FALSE}
install.packages("glmmADMB",
   repos=c("http://www.hafro.is/~arnima/repos", getOption("repos")))
install.packages("coefplot2",
    repos=c("http://www.math.mcmaster.ca/bolker/R", getOption("repos"))
```
May need to add `type="source"` to one or both of these.

Recommended versions (higher is OK):
```{r versions}
##      lme4  glmmADMB  MCMCglmm      blme  pbkrtest coefplot2      coda
##     1.1.7     0.7.7      2.18     1.0.2     0.3.8   0.1.3.2    0.16.1
##     aods3     bbmle
##     0.4.1    1.0.16
```
